### ISSUE TITLE
Implement Email Sending Functionality in React App

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/membrane-frontend#1]
**Description**:
As a part of our user authentication flow, we need the capability to send emails from our React application. This issue encompasses the necessary frontend functionality for the email-sending feature.

**Acceptance Criteria**:
1. Users should be able to input their email.
2. There should be validation in place to ensure only emails with our accepted domains are submitted.
3. On email submission, a POST request should be made to our Flask backend to trigger the email sending process.
4. Users should receive feedback on the UI if the email is sent successfully.
5. Users should also receive feedback if there are any errors, especially validation errors.

**Comment by rngadam** [comment]
I'm confused as to why this was closed as completed @CFIALeronB ? Isn't this what @k-allagbe is working on?

**Comment by CFIALeronB** [comment]
> I'm confused as to why this was closed as completed @CFIALeronB ? Isn't this what @k-allagbe is working on?

This issue is located in the membrane-frontend repository. Shouldn't this issue be in the membrane-backend repository instead?

**Comment by rngadam** [comment]
@CFIALeronB most user-visible feature request will have both a frontend issue and a backend issue. the frontend issue should probably come with mockups in the description while the backend issue will detail sequence diagrams and api endpoints.
