### ISSUE TITLE
Implement POST request for email sending with token

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/membrane-frontend#2]

**Comment by rngadam** [comment]
Another issue closed but still not delivered? @CFIALeronB

**Comment by CFIALeronB** [comment]
> Another issue closed but still not delivered? @CFIALeronB

Issue was resolved, but I don't believe was included in a commit description.

**Comment by rngadam** [comment]
@CFIALeronB can you provide a link to the source code lin where this is done then?

**Comment by CFIALeronB** [comment]
> @CFIALeronB can you provide a link to the source code lin where this is done then?

https://github.com/ai-cfia/membrane-frontend/commit/decac537c3adbefa65f11d873459761b89639b78
