### ISSUE TITLE
Update postCreateCommand in React TypeScript project

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/membrane-frontend#4]
### Description:
In our React TypeScript project, we currently have the following `postCreateCommand`:

"postCreateCommand": "npm install -g npm@9.8.1 --force",

We need to modify it to also include the installation of @saithodev/ts-appversion.

#### Proposed Change:

Update the postCreateCommand as follows:

"postCreateCommand": "npm install -g npm@9.8.1 --force && npm i @saithodev/ts-appversion"

Acceptance Criteria:

    Ensure the global npm version (9.8.1) is installed successfully.
    Ensure the @saithodev/ts-appversion package is installed in the project.

**Comment by rngadam** [comment]
@CFIALeronB you didn't reference this issue in your commit as "fixes #4" so this didn't close when you merged to main.

please follow the standard for commits .

close this issue if you've tested it is really fixed.
